# Generated by Django 3.1.1 on 2020-11-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBlog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('topic_title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'myblog',
            },
        ),
    ]
