# Generated by Django 3.1.1 on 2020-11-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20201120_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myblog',
            options={'ordering': ('id',)},
        ),
    ]
