# Generated by Django 3.1.1 on 2020-11-22 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20201121_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myblog',
            options={},
        ),
    ]
